### ISSUE TITLE
Queries do not run the same in Forge and Studio

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus-forge#59] opened 2020-08-14 14:14 UTC
Hi,

Here's the query in Studio, the self is required for technical reasons:
```sparql
  PREFIX vocab: <https://sandbox.bluebrainnexus.io/v1/vocabs/>
  PREFIX nxv: <https://bluebrain.github.io/nexus/vocabulary/>
  SELECT DISTINCT ?title ?self
  WHERE {
  ?id nxv:self ?self ;
      nxv:deprecated false ;
      vocab:title ?title ;
      ^vocab:movieId / vocab:tag "thought-provoking" .
  }
```

If I run this piece of code through the Forge, I get the following error:

> <error> TypeError: __init__() got multiple values for argument 'self'

I can fix it if I remove either the `?self` in the 'SELECT' or if I remove the assertion `nxv:self ?self ;`. Then the query runs fine.

**Comment by MFSY** [comment] 2020-10-24 14:43
Hi @adulbrich ,
The retrieved var names (incl. "self") are probably being passed to some RDFlib (a lib for working with rdf) function as a parameter and 'self' having a specific meaning in Python, this throws the error.

I'm afraid the variable name need not to be ?self. As such this is not a bug on the forge. I'm closing this issue.

**Closed by MFSY** 2020-10-24 14:43 UTC
Labels: bug, question
